# Use postgres/example user/password credentials
version: '3.1'

networks:
  tethys_network:
    external: true

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - tethys_network
    environment:
      POSTGRES_PASSWORD: gio

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
