[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "tethysapp-water_data_explorer"
version = "1.1.19"
description = "A tethys app that lets the user to visualize and query WSDL enpoints"
long_description = ""
keywords = ""
authors = [
    {name = "Giovanni Romero Bustamante", email = "gio.rombus@gmail.com"},
]
license = {text = "BSD 3-Clause License"}
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
include = ["tethysapp*"]

[tool.setuptools.package-data]
"*" = ["*.js", "*.css", "*.html", "*.png", "*.ico", "*.jpg", "*.gif", "*.svg", "*.json", "*.yml", "*.yaml", "*.txt", "*.xml", "*.csv", "*.geojson", "*.tif", "*.tiff"]
