version: "3.2"

# networks:
#   tethys_network:
#     external: true

services:
  tethys:
    build: .
    ports:
      - "80:80"
    # networks:
    #   - tethys_network
    environment:
      # TETHYS_DB_HOST: "172.17.0.1"
      # TETHYS_DB_SUPERUSER: "tethys_super"
      # TETHYS_DB_SUPERUSER_PASS: "pass"
      # TETHYS_SUPERUSER: "admin"
      # TETHYS_SUPERUSER_PASS: "cnr123"
      # CLIENT_MAX_BODY_SIZE: "100M"
      # PORTAL_SUPERUSER_NAME: "admin"
      # PORTAL_SUPERUSER_PASSWORD: "pass"
      # TETHYS_DB_NAME: "db"
      # TETHYS_DB_USERNAME: "tethys_default"
      # TETHYS_DB_PASSWORD: "pass"
      # TETHYS_DB_PORT: "5432"
      # TITLE: "WHOS"
      # POSTGRES_PASSWORD: gio
      TETHYS_DB_SUPERUSER: "tethys_super"
      TETHYS_DB_SUPERUSER_PASS: "pass"
      TETHYS_SUPERUSER: "admin"
      TETHYS_SUPERUSER_PASS: "cnr123"
      CLIENT_MAX_BODY_SIZE: "100M"
      PORTAL_SUPERUSER_NAME: "admin"
      PORTAL_SUPERUSER_PASSWORD: "pass"
      TETHYS_DB_NAME: "tethys_default"
      TETHYS_DB_USERNAME: "tethys_default"
      TETHYS_DB_PASSWORD: "pass"
      TETHYS_DB_PORT: "5432"
      TITLE: "WHOS"
      BYPASS_TETHYS_HOME_PAGE: "True"
      ENABLE_OPEN_PORTAL: "True"
      AXES_FAILURE_LIMIT: 10
      #Please change the ALLOWED HOST to anything that is needed following this example #
      ALLOWED_HOSTS: "\"[localhost, 127.0.0.1, 97.67.251.194, 62.245.16.117]\""

    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
